twilio: # Twilio gateway configuration
  accountId: AC44fd87c05ce4983c8d6505fb8718140b
  accountToken: 001a2f8638df5e92a70db09e10861164
  numbers:
    - +16617044882
    - #(620) 682-9903
    - #+16206829903
    - #+16206829903
    - #+1 201-347-7543
    - # Third number
    - # ...
    - # Nth number
  messagingServicesId: 
  localDomain: howzit.observanteye.com:4443

push:
  queueSize: 1000

#redphone:
  #authKey: # Deprecated

turn: # TURN server configuration
  secret: turnserversharedsecret
  uris: ["stun:stun.l.google.com:19302"]

cache: # Redis server configuration for cache cluster
  url: "redis://localhost:6379/1"
  replicaUrls: 
      - "redis://localhost:6379/2"
directory: # Redis server configuration for directory cluster
  url: "redis://localhost:6379/3"
  replicaUrls: 
      - "redis://localhost:6379/4"

messageCache:  
  redis: {url: "redis://localhost:6379/5", replicaUrls: ["redis://localhost:6379/6"]} 
  cacheRate: 1 
  persistDelayMinutes: 10 

messageStore: # Postgresql database configuration for message store
  driverClass: org.postgresql.Driver
  user: "postgres"
  password: "admin@123"
  url: "jdbc:postgresql://127.0.0.1:5432/messagedb"

attachments: # AWS S3 configuration
  accessKey: RX5E19CDCZ4GK4KLLZX9
  accessSecret: elYYT3xdFhzgbNkYtg5QKcHq/mkqHdj8Cbk+dWbj
  bucket: howzit-attachment-bucket

profiles: # AWS S3 configuration
  accessKey: RX5E19CDCZ4GK4KLLZX9
  accessSecret: elYYT3xdFhzgbNkYtg5QKcHq/mkqHdj8Cbk+dWbj
  bucket: howzit-profile-bucket
  region: us-east-1

database: # Postgresql database configuration
  driverClass: org.postgresql.Driver
  user: "postgres"
  password: "admin@123"
  url: "jdbc:postgresql://127.0.0.1:5432/accountsdb"

#apn: # Apple Push Notifications configuration
  #bundleId:
  #pushCertificate:
  #pushKey:

gcm: # GCM Configuration
  senderId: 32116374335
  apiKey: AIzaSyCAVeOAKrfTFGPRX-KjNwQXY8KoYj3f8G4
      
pushScheduler:                               
  url: "redis://localhost:6379/7"       
  replicaUrls: 
    - "redis://localhost:6379/8"